import { Providers } from "@/components/providers";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/auth';
import { extractRouterConfig } from "uploadthing/server";
import { appFileRouter } from "./api/uploadthing/core";
import { Toaster } from "@/components/ui/sonner";
import { Modals } from "@/components/modals";
;
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 const session = await auth();
  return (
   <SessionProvider session={session}>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Providers>
        <NextSSRPlugin routerConfig={extractRouterConfig(appFileRouter)} />
        <Toaster theme="light" closeButton richColors />
        <Modals/>
         {children}
         </Providers>
      </body>
    </html>
    </SessionProvider>
  );
}
